const mockData = [
  // Julho
  {
    Id: 1,
    "Nome Pessoa": "João Silva",
    "Cargo Pessoa": "Gerente",
    "Centro de Custo": "Bar",
    "Tipo Pagamento": "Entrada",
    Produto: "Bebidas",
    Data: "2024-07-01",
    "Forma de Pagamento": "Cartão",
    valor: 5100.00,
  },
  {
    Id: 2,
    "Nome Pessoa": "Maria Santos",
    "Cargo Pessoa": "Instrutora",
    "Centro de Custo": "Futebol",
    "Tipo Pagamento": "débito",
    Produto: "Salário",
    Data: "2024-07-05",
    "Forma de Pagamento": "Transferência",
    valor: 1500.00,
  },
  {
    Id: 3,
    "Nome Pessoa": "Carlos Pereira",
    "Cargo Pessoa": "Segurança",
    "Centro de Custo": "Segurança",
    "Tipo Pagamento": "Entrada",
    Produto: "Serviço",
    Data: "2024-07-08",
    "Forma de Pagamento": "Dinheiro",
    valor: 200.00,
  },
  {
    Id: 4,
    "Nome Pessoa": "Ana Oliveira",
    "Cargo Pessoa": "Recepcionista",
    "Centro de Custo": "Recepção",
    "Tipo Pagamento": "débito",
    Produto: "Salário",
    Data: "2024-07-10",
    "Forma de Pagamento": "Cartão",
    valor: 1500.00,
  },
  {
    Id: 5,
    "Nome Pessoa": "Paulo Mendes",
    "Cargo Pessoa": "Cozinheiro",
    "Centro de Custo": "Restaurante",
    "Tipo Pagamento": "Entrada",
    Produto: "Alimentos",
    Data: "2024-07-12",
    "Forma de Pagamento": "Transferência",
    valor: 300.00,
  },
  {
    Id: 6,
    "Nome Pessoa": "Laura Ferreira",
    "Cargo Pessoa": "Instrutora",
    "Centro de Custo": "Yoga",
    "Tipo Pagamento": "débito",
    Produto: "Material",
    Data: "2024-07-14",
    "Forma de Pagamento": "Cartão",
    valor: 250.00,
  },
  {
    Id: 7,
    "Nome Pessoa": "Roberto Costa",
    "Cargo Pessoa": "Gerente",
    "Centro de Custo": "Administração",
    "Tipo Pagamento": "Entrada",
    Produto: "Serviço",
    Data: "2024-07-16",
    "Forma de Pagamento": "Dinheiro",
    valor: 400.00,
  },
  {
    Id: 8,
    "Nome Pessoa": "Juliana Mendes",
    "Cargo Pessoa": "Coordenadora",
    "Centro de Custo": "Beach Tênis",
    "Tipo Pagamento": "débito",
    Produto: "Material",
    Data: "2024-07-20",
    "Forma de Pagamento": "Cartão",
    valor: 300.00,
  },
  {
    Id: 9,
    "Nome Pessoa": "Fernando Almeida",
    "Cargo Pessoa": "Instrutor",
    "Centro de Custo": "Natação",
    "Tipo Pagamento": "Entrada",
    Produto: "Equipamento",
    Data: "2024-07-22",
    "Forma de Pagamento": "Transferência",
    valor: 500.00,
  },
  {
    Id: 10,
    "Nome Pessoa": "Gabriela Lima",
    "Cargo Pessoa": "Atendente",
    "Centro de Custo": "Atendimento",
    "Tipo Pagamento": "débito",
    Produto: "Salário",
    Data: "2024-07-25",
    "Forma de Pagamento": "Cartão",
    valor: 1500.00,
  },
  // Agosto
  {
    Id: 11,
    "Nome Pessoa": "Pedro Henrique",
    "Cargo Pessoa": "Gerente",
    "Centro de Custo": "Bar",
    "Tipo Pagamento": "Entrada",
    Produto: "Bebidas",
    Data: "2024-08-01",
    "Forma de Pagamento": "Cartão",
    valor: 120.00,
  },
  {
    Id: 12,
    "Nome Pessoa": "Renata Silva",
    "Cargo Pessoa": "Instrutora",
    "Centro de Custo": "Futebol",
    "Tipo Pagamento": "débito",
    Produto: "Salário",
    Data: "2024-08-05",
    "Forma de Pagamento": "Transferência",
    valor: 1600.00,
  },
  {
    Id: 13,
    "Nome Pessoa": "Marcos Pereira",
    "Cargo Pessoa": "Segurança",
    "Centro de Custo": "Segurança",
    "Tipo Pagamento": "Entrada",
    Produto: "Serviço",
    Data: "2024-08-08",
    "Forma de Pagamento": "Dinheiro",
    valor: 250.00,
  },
  {
    Id: 14,
    "Nome Pessoa": "Bianca Oliveira",
    "Cargo Pessoa": "Recepcionista",
    "Centro de Custo": "Recepção",
    "Tipo Pagamento": "débito",
    Produto: "Salário",
    Data: "2024-08-10",
    "Forma de Pagamento": "Cartão",
    valor: 1500.00,
  },
  {
    Id: 15,
    "Nome Pessoa": "Lucas Mendes",
    "Cargo Pessoa": "Cozinheiro",
    "Centro de Custo": "Restaurante",
    "Tipo Pagamento": "Entrada",
    Produto: "Alimentos",
    Data: "2024-08-12",
    "Forma de Pagamento": "Transferência",
    valor: 350.00,
  },
  {
    Id: 16,
    "Nome Pessoa": "Carla Ferreira",
    "Cargo Pessoa": "Instrutora",
    "Centro de Custo": "Yoga",
    "Tipo Pagamento": "débito",
    Produto: "Material",
    Data: "2024-08-14",
    "Forma de Pagamento": "Cartão",
    valor: 200.00,
  },
  {
    Id: 17,
    "Nome Pessoa": "Ricardo Costa",
    "Cargo Pessoa": "Gerente",
    "Centro de Custo": "Administração",
    "Tipo Pagamento": "Entrada",
    Produto: "Serviço",
    Data: "2024-08-16",
    "Forma de Pagamento": "Dinheiro",
    valor: 450.00,
  },
  {
    Id: 18,
    "Nome Pessoa": "Carolina Mendes",
    "Cargo Pessoa": "Coordenadora",
    "Centro de Custo": "Beach Tênis",
    "Tipo Pagamento": "débito",
    Produto: "Material",
    Data: "2024-08-20",
    "Forma de Pagamento": "Cartão",
    valor: 300.00,
  },
  {
    Id: 19,
    "Nome Pessoa": "Leonardo Almeida",
    "Cargo Pessoa": "Instrutor",
    "Centro de Custo": "Natação",
    "Tipo Pagamento": "Entrada",
    Produto: "Equipamento",
    Data: "2024-08-22",
    "Forma de Pagamento": "Transferência",
    valor: 600.00,
  },
  {
    Id: 20,
    "Nome Pessoa": "Patrícia Lima",
    "Cargo Pessoa": "Atendente",
    "Centro de Custo": "Atendimento",
    "Tipo Pagamento": "débito",
    Produto: "Salário",
    Data: "2024-08-25",
    "Forma de Pagamento": "Cartão",
    valor: 1600.00,
  },
  // Setembro
  {
    Id: 21,
    "Nome Pessoa": "Bruno Silva",
    "Cargo Pessoa": "Gerente",
    "Centro de Custo": "Bar",
    "Tipo Pagamento": "Entrada",
    Produto: "Bebidas",
    Data: "2024-09-01",
    "Forma de Pagamento": "Cartão",
    valor: 110.00,
  },
  {
    Id: 22,
    "Nome Pessoa": "Aline Santos",
    "Cargo Pessoa": "Instrutora",
    "Centro de Custo": "Futebol",
    "Tipo Pagamento": "débito",
    Produto: "Salário",
    Data: "2024-09-05",
    "Forma de Pagamento": "Transferência",
    valor: 1700.00,
  },
  {
    Id: 23,
    "Nome Pessoa": "Gustavo Pereira",
    "Cargo Pessoa": "Segurança",
    "Centro de Custo": "Segurança",
    "Tipo Pagamento": "Entrada",
    Produto: "Serviço",
    Data: "2024-09-08",
    "Forma de Pagamento": "Dinheiro",
    valor: 250.00,
  },
  {
    Id: 24,
    "Nome Pessoa": "Marcos Hugo",
    "Cargo Pessoa": "Segurança",
    "Centro de Custo": "Segurança",
    "Tipo Pagamento": "Entrada",
    Produto: "Picole",
    Data: "2024-09-08",
    "Forma de Pagamento": "Dinheiro",
    valor: 250.00,
  },
  {
    Id: 25,
    "Nome Pessoa": "Marcos Hugo",
    "Cargo Pessoa": "Segurança",
    "Centro de Custo": "Bar",
    "Tipo Pagamento": "Entrada",
    Produto: "gatorade",
    Data: "2024-09-08",
    "Forma de Pagamento": "Dinheiro",
    valor: 20.00,
  },

  {
    Id: 26,
    "Nome Pessoa": "Vitoria",
    "Cargo Pessoa": "Recepcionista",
    "Centro de Custo": "bar",
    "Tipo Pagamento": "débito",
    Produto: "caderno",
    Data: "2024-06-06",
    "Forma de Pagamento": "Pix",
    valor: 1450.00,
  },

  {
    Id: 26,
    "Nome Pessoa": "mirilla",
    "Cargo Pessoa": "cliente",
    "Centro de Custo": "Restaurante",
    "Tipo Pagamento": "Entrada",
    Produto: "camarao intenacional",
    Data: "2024-06-06",
    "Forma de Pagamento": "Pix",
    valor: 3000,
  },

  {
    Id: 26,
    "Nome Pessoa": "Marcia Rejane",
    "Cargo Pessoa": "cliente",
    "Centro de Custo": "Consessionaria",
    "Tipo Pagamento": "Entrada",
    Produto: "BYD - Dolphing",
    Data: "2024-07-20",
    "Forma de Pagamento": "Pix",
    valor: 2000,
  },

  {
    Id: 26,
    "Nome Pessoa": "Rafael",
    "Cargo Pessoa": "cliente",
    "Centro de Custo": "Consessionaria",
    "Tipo Pagamento": "Entrada",
    Produto: "BYD - Dolphing",
    Data: "2024-07-20",
    "Forma de Pagamento": "Pix",
    valor: 2000,
  },


];

module.exports = mockData;
